project:
  type: default
  output-dir: .

format:
  clean-revealjs:
    theme: [default, _extensions/clean/clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    self-contained: false
    output-file: index.html
    chalkboard:
      theme: chalkboard
      grid: false
      boardmarkers: false
      navigation: true
      buttons: true
    multiplex: false
    scrollable: true
    footer: '<a href="https://github.com/JacobKMcPherson/template_quarto_presentation" target="_blank">🔗 View on GitHub</a>'